name: automatizacion_hidroponia
region: nyc
services:
  - name: web
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    run_command: gunicorn "app:create_app()"
    envs:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "supersecreto"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}   # referencia a tu PostgreSQL gestionado en DO
      - key: MQTT_BROKER
        value: test.mosquitto.org
      - key: MQTT_PORT
        value: 8080
      - key: MQTT_TOPIC
        value: hidroponia/valvula/estado
      - key: CLIENT_ID
        value: esp32_valvula_01