"""empty message

Revision ID: 18e02f77e90a
Revises: 
Create Date: 2025-09-14 09:25:00.399039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e02f77e90a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_bomba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estad_bomba', sa.String(length=50), nullable=False),
    sa.Column('tiempo_llenado', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('estado_bomba')
    # ### end Alembic commands ###
