"""empty message

Revision ID: 9db099182ecf
Revises: 18e02f77e90a
Create Date: 2025-09-14 09:33:09.013550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db099182ecf'
down_revision = '18e02f77e90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_bomba', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=False))
        batch_op.alter_column('tiempo_llenado',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('estad_bomba')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_bomba', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estad_bomba', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('tiempo_llenado',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
